refactor: unify all forums into a single XenForo crawler
jbsparrow/CyberDropDownloader pull request #354
Opened 2024-12-04 21:00 UTC by NTFSvolume

Defines a single `XenforoCrawler` to deduce code duplication. The code on every crawler was basically the same

However, given that each forum uses slightly different CSS selectors, using a single crawler to manage all of them will make it really annoying to work with. What i did instead was create a base `XenforoCrawler` and each forum inherit from it, overriding key properties like the `primary_base_domain` and the CSS selectors they use

2024-12-05 21:48 UTC, jbsparrow commented
It's beautiful 😻

2024-12-11 05:09 UTC, NTFSvolume commented
Tested on SMG and SC. Everything seems to be working

2024-12-11 05:28 UTC, NTFSvolume commented
Added a fix to the chevereto profile scraper. It’s unrelated to this PR, but I found it while testing and it’s a simple one-line fix.

2024-12-11 15:47 UTC, jbsparrow approved these changes
I don't really use any of the forums except SimpCity but I'll look into making accounts and testing the others before we merge.

2024-12-11 16:37 UTC, jbsparrow commented
- [ ] Test Celebforum
- [ ] Test F95zone
- [ ] Test Leakedmodels
- [ ] Test Nudostar
- [ ] Test Xbunker
- [ ] Test SimpCity
- [ ] Test Socialmediagirls

2024-12-11 19:00 UTC, jbsparrow requested changes
Now F95zone is the only forum that has some issues. With the selector I added for f95zone attachments, we also grab thumbnails. F95zone also has a redirect protection thing, we can easily get the correct URL from it but I'm not sure exactly where in the code we would put the extractor for it.

2024-12-11 19:00 UTC, jbsparrow commented on cyberdrop_dl/scraper/crawlers/f95zone_crawler.py
> +        date=Selector("time", "data-time"),
```suggestion
        date=Selector("time", "data-time"),
        number=Selector("a[class=u-concealed]", "href"),
```

2024-12-11 19:00 UTC, jbsparrow commented on cyberdrop_dl/scraper/crawlers/nudostar_crawler.py
> +        date=Selector("time", "data-time"),
```suggestion
        date=Selector("time", "data-time"),
        number=Selector("a[class=u-concealed]", "href"),
```

2024-12-11 19:00 UTC, jbsparrow commented on cyberdrop_dl/scraper/crawlers/xenforo_crawler.py
> +        self.attachment_url_hosts = ["smgmedia"]
```suggestion
        self.attachment_url_hosts = ["smgmedia", "attachments.f95zone"]
```

2024-12-11 19:58 UTC, NTFSvolume commented
I think i know what the issue is. F95zone had a different logic for `handle_confirmation_link` . I renamed that function to `handle_link_confirmation2` but it's never used in the current crawler cause i didn't know why it was different. 

We can use that one as an override of the base one in `F95zoneCrawler`.

https://github.com/jbsparrow/CyberDropDownloader/blob/95a6e0662a320dea066776353ad1d86dff993ac3/cyberdrop_dl/scraper/crawlers/xenforo_crawler.py#L303-L314

2024-12-11 20:12 UTC, NTFSvolume commented
Pushed a commit with the override. Please try again with F95Zone

2024-12-11 20:23 UTC, NTFSvolume commented
The old F95Zone called `handle_link_confirmation` if the link had the word `masked`, but i think that's too generic. A regular URL could have that word as well. Can you confirm what the link looks like? maybe `masked` is a part of the path and we can limit the condition a bit more

2024-12-11 20:37 UTC, NTFSvolume commented
Also, the link confirmation override makes a random call to get the soup of the link but the result is not saved anywhere. Pretty sure is not necessary, but I kept it as is to match the original logic.

2024-12-13 17:22 UTC, jbsparrow commented
For handling the confirmation we can just skip the redirect by extracting the target url from the redirect url. Wouldn't that be more ideal?

2024-12-13 18:48 UTC, jbsparrow approved these changes

2024-12-13 18:50 UTC, jbsparrow commented
Fixed F95zone and added a function for checking if a URL is a confirmation link so that we can define it per-crawler.

2024-12-13 19:58 UTC, merged